Renamed steps for consistency, #SKIP

diff --git a/.github/workflows/deployment-pipeline.yml b/.github/workflows/deployment-pipeline.yml
--- a/.github/workflows/deployment-pipeline.yml
+++ b/.github/workflows/deployment-pipeline.yml
@@ -40,15 +40,15 @@ jobs:
           TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
           SECRET: ${{ secrets.SECRET }}
         run: cd bloglist-backend && npm run test &> out-test-logs.txt
-      - name: store test logs to CONTENT_ENV
+      - name: backend - api tests - store logs to variable
         run: |
           echo 'CONTENT_ENV<<EOF' >> $GITHUB_ENV
           cat out-test-logs.txt >> $GITHUB_ENV
           echo 'EOF' >> $GITHUB_ENV
         working-directory: ./bloglist-backend
-      - name: show the logs
+      - name: backend - api tests - show logs
         run: echo "$CONTENT_ENV"
-      - name: exit if tests failed
+      - name: backend - api tests - exit 1 if logs contain 'FAIL'
         if: ${{contains(join(env.CONTENT_ENV), 'FAIL')}}
         run: exit 1
       - name: e2e tests
